workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    environment:
      vars:
        XCODE_WORKSPACE: "DeepLiveCam.xcworkspace"
        XCODE_SCHEME: "DeepLiveCam"
        BUNDLE_ID: "com.deeplivecam.app"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build for iOS Simulator
        script: |
          # Build for iOS Simulator (no code signing required)
          xcodebuild clean -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build -derivedDataPath $PWD/build/DerivedData
          
          # Find and copy the .app bundle to build directory
          mkdir -p $PWD/build
          
          # Look for the .app file in the derived data directory
          APP_PATH=$(find $PWD/build/DerivedData -name "DeepLiveCam.app" -type d | head -1)
          
          if [ -n "$APP_PATH" ]; then
            echo "Found app at: $APP_PATH"
            cp -r "$APP_PATH" $PWD/build/
            
            # Create a zip file for easier download
            cd $PWD/build
            zip -r DeepLiveCam-Simulator.zip DeepLiveCam.app
            echo "Build completed successfully!"
          else
            echo "Error: DeepLiveCam.app not found in build output"
            echo "Contents of DerivedData:"
            find $PWD/build/DerivedData -name "*.app" -type d
            exit 1
          fi
    artifacts:
      - build/DeepLiveCam.app
      - build/DeepLiveCam-Simulator.zip
