workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    environment:
      vars:
        XCODE_WORKSPACE: "DeepLiveCam.xcworkspace"
        XCODE_SCHEME: "DeepLiveCam"
        BUNDLE_ID: "com.deeplivecam.app"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build for iOS Simulator
        script: |
          # Build for iOS Simulator (no code signing required)
          xcodebuild clean -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build -derivedDataPath $PWD/build/DerivedData
          
          # Copy the .app bundle to build directory
          mkdir -p $PWD/build
          cp -r $PWD/build/DerivedData/Build/Products/Debug-iphonesimulator/DeepLiveCam.app $PWD/build/
          
          # Create a zip file for easier download
          cd $PWD/build
          zip -r DeepLiveCam-Simulator.zip DeepLiveCam.app
    artifacts:
      - build/DeepLiveCam.app
      - build/DeepLiveCam-Simulator.zip
