workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "DeepLiveCam.xcworkspace"
        XCODE_SCHEME: "DeepLiveCam"
        BUNDLE_ID: "com.deeplivecam.app"
        TEAM_ID: "F8WF6PT8DC"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild clean -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive -archivePath $PWD/build/DeepLiveCam.xcarchive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/DeepLiveCam.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build
    artifacts:
      - build/*.ipa
